export const ALL_DEPARTMENTS_REQUEST = "ALL_DEPARTMENTS_REQUEST";
export const ALL_DEPARTMENTS_SUCCESS = "ALL_DEPARTMENTS_SUCCESS";
export const ALL_DEPARTMENTS_FAIL = "ALL_DEPARTMENTS_FAIL";
export const CLEAR_ERRORS = "CLEAR_ERRORS";