export const ALL_HARDWARE_REQUEST = "ALL_HARDWARE_REQUEST";
export const ALL_HARDWARE_SUCCESS = "ALL_HARDWARE_SUCCESS";
export const ALL_HARDWARE_FAIL = "ALL_HARDWARE_FAIL";
export const CLEAR_ERRORS = "CLEAR_ERRORS";